version: "3.8"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - "5173:5173"
        volumes:
            - node_modules:/simple-customer-info-api/node_modules
            - ./src:/simple-customer-info-api/src
            - .:/simple-customer-info-api
        depends_on:
            - backend

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "5000:5000"
        volumes:
            - node_modules:/simple-customer-info-api/node_modules
            - ./server:/simple-customer-info-api/server
            - .:/simple-customer-info-api

volumes:
    node_modules:
