FROM node:20-alpine
WORKDIR /simple-customer-info-api

# Copy necessary files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy backend code
COPY server/ ./server

# Start the backend server
CMD ["yarn", "start"]
EXPOSE 5000
